name: Build, Push and Deploy from ECR

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      # (1) 소스 코드 체크아웃
      - name: Check out repository
        uses: actions/checkout@v2

      # (2) JDK 21 설치 (Gradle 빌드용)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # (3) Gradle 빌드
      - name: Build with Gradle
        run: |
          ./gradlew clean build

      # (4) AWS 자격증명 설정 (GitHub Secrets → ECR에 Push할 권한)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # (5) ECR 로그인
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # (6) Docker Build & Push (ECR)
      - name: Build and Push to ECR
        run: |
          docker buildx build --platform linux/amd64 --load \
            -t 533267033034.dkr.ecr.ap-northeast-2.amazonaws.com/jobfair:latest .
          docker push 533267033034.dkr.ecr.ap-northeast-2.amazonaws.com/jobfair:latest

      # (7) SSH로 EC2 접속 → ECR 이미지 Pull & docker run
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 3.36.249.253                 # EC2 Public IP (예시)
          username: ubuntu                   # EC2 사용자명 (예시)
          key: ${{ secrets.EC2_SSH_KEY }}    # GitHub Secrets에 저장된 PEM 키
          script: |
            # 1) ECR 로그인 (EC2가 IAM Role로 권한을 갖고 있다고 가정)
            aws ecr get-login-password --region ap-northeast-2 \
              | docker login --username AWS \
              --password-stdin 533267033034.dkr.ecr.ap-northeast-2.amazonaws.com

            # 2) Pull 최신 이미지
            docker pull 533267033034.dkr.ecr.ap-northeast-2.amazonaws.com/jobfair:latest

            # 3) 기존 컨테이너 종료 및 제거 (이미 실행 중이면)
            docker stop jobfair || true
            docker rm jobfair || true

            # 4) 새 컨테이너 실행
            #    - 예) 호스트 80 -> 컨테이너 8080 포트 매핑
            #    - name: jobfair (컨테이너 이름)
            docker run -d \
              --name jobfair \
              -p 80:8080 \
              533267033034.dkr.ecr.ap-northeast-2.amazonaws.com/jobfair:latest
