name: Build and Push Docker Image

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # 1단계: 리포지토리 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2단계: JDK 21 설치 (필요한 경우)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3단계: Gradle 빌드
      - name: Build with Gradle
        run: |
          ./gradlew build

      # 4단계: AWS 자격 증명 구성 (GitHub Secrets에 저장된 ACCESS_KEY_ID, SECRET_ACCESS_KEY 사용)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2   # ECR 리포지토리가 위치한 리전

      # 5단계: AWS ECR에 로그인 (ECR에 푸시하기 위한 사전 인증)
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 6단계: 깃허브 레포지토리 내 Dockerfile을 사용하여 도커 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t 533267033034.dkr.ecr.ap-northeast-2.amazonaws.com/jobfair .

      # 7단계: 빌드된 도커 이미지를 AWS ECR에 푸시
      - name: Push Docker image
        run: |
          docker push 533267033034.dkr.ecr.ap-northeast-2.amazonaws.com/jobfair
