name: Build, Push and Deploy Docker Image

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # 1단계: 리포지토리 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2단계: JDK 21 설치 (Gradle 빌드용)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3단계: Gradle 빌드
      - name: Build with Gradle
        run: |
          ./gradlew build

      # 4단계: Docker Build & Push (Docker Hub에 푸시 예시)
      - name: Build Docker image
        run: |
          # Docker Hub 로그인 (access token 필요 시 secrets 활용)
          # docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          # 이미지를 linux/amd64로 빌드하고 local에 로드(load) 후, jeongheumchoi/clubfair-be:0.0.1 태그로 푸시
          docker buildx build --platform linux/amd64 --load --tag jeongheumchoi/clubfair-be:0.0.1 .
          docker push jeongheumchoi/clubfair-be:0.0.1

      # 5단계: EC2에 SSH 접속 → 이미지 Pull → /home/ubuntu/deploy.sh 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 3.36.249.253            
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull jeongheumchoi/clubfair-be:0.0.1
            chmod +x /home/ubuntu/deploy.sh
            /home/ubuntu/deploy.sh
